name: 🚀 Feature Request / Question
description: Request a new feature or ask a general question
title: "[FEATURE/QUESTION] "
labels: ["enhancement", "question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature or ask a question!
        Please provide as much detail as possible to help us understand your needs.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief summary of your feature request or question
      placeholder: What would you like to see or know?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of your feature request or question
      placeholder: |
        - What problem does this solve?
        - How would this feature work?
        - Why is this important to you?
        - Any additional context or examples?
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that might be helpful
      placeholder: Any additional information that might help us understand your request
